language: node_js
node_js:
  - '0.10'
  - '0.12'
before_script:
  - npm install -g grunt-cli
script:
  - grunt test
  - grunt coffeelint
  - grunt coveralls
notifications:
  webhooks:
    secure: "SC9pCYAPqeRwhccB4e+bifnTw5jtAyj8uLfZPOiDh23nnMzsb6RQfZqEp4mwURqlpPBsbTtpUWzR/ehGyev/gaG3qFomkRMDNvL14cewaHEv4VTtLIwkrTaQjBPGp4vkwfvOc+arxOVoPy7cqaAShXvADH1Ck0rveTySuRXZi9M="
